# Generated by Django 4.2.2 on 2025-06-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('stress_level', models.CharField(max_length=20)),
                ('diagnosed', models.CharField(max_length=50)),
                ('symptoms', models.TextField()),
                ('other_issues', models.TextField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
