# Generated by Django 4.2.2 on 2025-06-25 17:55

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CKEditorContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
