# Generated by Django 4.2.2 on 2025-06-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_ckeditorcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
